<a href="https://colab.research.google.com/github/dl0312/PS/blob/master/sp_pj4/p4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import math
from decimal import *

size = int(input())
np_ary = np.random.random((size, size))
for i in range(len(np_ary)):
    for j in range(len(np_ary[i])):
        np_ary[i][j] = Decimal(np_ary[i][j]).quantize(Decimal('1.00'))

print(np_ary)

rows, columns = np_ary.shape

row_idx = rows // 2
column_idx = columns // 2
print(np_ary[:row_idx * 2, :column_idx * 2].reshape(row_idx, 2, column_idx, 2).max(axis=(1, 3)))

4
[[0.63 0.81 0.01 0.75]
 [0.26 0.78 0.52 0.58]
 [0.31 0.14 0.77 0.98]
 [0.65 0.49 0.4  0.34]]
[[0.81 0.75]
 [0.65 0.98]]
